version: 2
project_name: ingress-nginx-migration
before:
  hooks:
    - go mod tidy
builds:
  - id: ingress-nginx-migration
    main: ./cmd/ingress-nginx-migration
    binary: ingress-nginx-migration
    env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags: ["-s -w -X main.version={{.Version}}"]
archives:
  - id: default
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: rohitsingh4334
    name: nginx-ingress-to-istio
